Fix DEBUG_GENERATION build (#19383)
### Description
Currently, ORT will fail a build when the flag DEBUG_GENERATION is set
to 1 (used to debug BeamSearch and GreedySearch) in
[console_dumper.h](https://github.com/microsoft/onnxruntime/blob/d113286962280be1dc079f472d55ce49484b3892/onnxruntime/contrib_ops/cpu/utils/console_dumper.h#L12)
with the following error:


`onnxruntime/onnxruntime/contrib_ops/cpu/transformers/logits_processor.h:270:15:
error: ‘DumpScores’ was not declared in this scope`

This is because it is defined in `logits_processor.cc`, and a debugging
artifact was passed in an earlier PR where this function is called from
`logits_processor.h` before it is defined
[[link](https://github.com/microsoft/onnxruntime/blob/4f1e1bec6a79c2e8703ee20e03f367b5feea2346/onnxruntime/contrib_ops/cpu/transformers/logits_processor.h#L270)].
Builds with the flag have been broken since that PR was merged.

This PR moves DumpScores() definition from `logits_processor.cc` to
`logits_processor.h` so that all debug statements can be used correctly
in `logits_processor.cc` and `logits_processor.h` and build succeeds
with this debug flag.

---------

Co-authored-by: Peter McAughan <petermca@microsoft.com>