[webgpu] Fix build break in matmul_nbits.cc (#25806)
### Description

Fix build break caused by warning C4702: unreachable code.

```
onnxruntime\contrib_ops\webgpu\quantization\matmul_nbits.cc(95,1): error C2220: the following warning is treated
 as an error [C:\code\o3\build_main\Debug\onnxruntime_providers_webgpu.vcxproj]
onnxruntime\contrib_ops\webgpu\quantization\matmul_nbits.cc(95,1): warning C4702: unreachable code [C:\code\o3\b
uild_main\Debug\onnxruntime_providers_webgpu.vcxproj]
```

Seems the CI pipeline does not catch this.