Fix swapped count and value arguments to `std::vector` constructor. (#25706)
### Description
<!-- Describe your changes. -->

Fix swapped value and count arguments to `std::vector` constructor.

The `std::vector` constructor signature is:
`vector( size_type count, const T& value, const Allocator& alloc =
Allocator() );`

https://en.cppreference.com/w/cpp/container/vector/vector.html

### Motivation and Context
<!-- - Why is this change required? What problem does it solve?
- If it fixes an open issue, please link to the issue here. -->

Fix issue discovered after enabling warning.

```
Error: E:\_work\onnxruntime\onnxruntime\onnxruntime\test\providers\tensorrt\tensorrt_basic_test.cc(688,34): error C2220: the following warning is treated as an error [E:\_work\_temp\build\RelWithDebInfo\onnxruntime_provider_test.vcxproj]
Warning: E:\_work\onnxruntime\onnxruntime\onnxruntime\test\providers\tensorrt\tensorrt_basic_test.cc(688,34): warning C4244: 'argument': conversion from 'float' to 'const unsigned __int64', possible loss of data [E:\_work\_temp\build\RelWithDebInfo\onnxruntime_provider_test.vcxproj]
```