[Build] skip python tests when python version is 3.14 (#26500)
This is a follow up change for
https://github.com/microsoft/onnxruntime/pull/26397:
(1) Enable python 3.14 for webgpu package
(2) Skip python tests for python 3.14 just like in python cuda package
pipelines.

onnx package does not support python 3.14 right now, so python tests
depending on onnx will fail. Example error in python package pipeline:
```
Traceback (most recent call last):
  File "E:\_work\1\s\build\Release\Release\onnx_backend_test_series.py", line 14, in <module>
    import onnx
ModuleNotFoundError: No module named 'onnx'
```

This is a temporary walkaround to unblock python packaging pipeline for
python 3.14. We can re-enable the test after onnx next release (in a few
weeks?)