Add LSX support for S8S8 and S8U8 GEMM kernels (#24397)
### Description

- Add missing support for S8S8/S8U8 in GEMM kernels of LSX
- Add new dispatch entries for S8S8 and S8U8 GEMM operations in mlasi.h
- Extend MLAS_PLATFORM struct to include S8S8 and S8U8 dispatch pointers
for LSX

### Motivation and Context

To fix [build
error](https://github.com/lcpu-club/loongarch-packages/pull/526#issuecomment-2723313028)
on loong64:
```
error: ‘struct MLAS_PLATFORM’ has no member named ‘GemmS8S8Dispatch’
```

### Test status

Tested on Arch Linux for Loong64, here is the build log:

*
[onnxruntime-1.20.2-7.1-loong64-build.log](https://github.com/user-attachments/files/19710083/onnxruntime-1.20.2-7.1-loong64-build.log)

Signed-off-by: Zhou Qiankang <wszqkzqk@qq.com>