A temporary fix for layout opt level to unblock react native android CI (#24948)
### Description

A temporary fix to unblock react native android CI.

### Motivation and Context

After https://github.com/microsoft/onnxruntime/pull/24726 is merged to
main, react native android CI starts failing with error like

```
/mnt/vss/_work/1/s/js/react_native/e2e/node_modules/onnxruntime-react-native/android/src/main/java/ai/onnxruntime/reactnative/OnnxruntimeModule.java:329: error: cannot find symbol
              {"layout", SessionOptions.OptLevel.LAYOUT_OPT},
                                                ^
  symbol:   variable LAYOUT_OPT
  location: class OptLevel
```

The LAYOUT_OPT is defined in
https://github.com/microsoft/onnxruntime/blob/b7bc77c6f319ee128fb73b6a03c0bcedbc13e888/java/src/main/java/ai/onnxruntime/OrtSession.java#L656.

The root cause of the build error is unknown. Since the layout level is
just added, so it is not used by users. It is safe to comment the line
to unblock the pipeline.