Add DNNL github workflow (#24011)
### Description
Add DNNL github workflow which is migrated from "Windows CPU CI
pipeline" from Azure DevOps.
This PR also adds "--build_nuget" to test the C# part. 
However, then I hit an error when building the tests in
"test\Microsoft.ML.OnnxRuntime.Tests.NetCoreApp\Microsoft.ML.OnnxRuntime.Tests.NetCoreApp.csproj".
The error message was:

```
D:\a\_work\onnxruntime\onnxruntime\csharp\test\Microsoft.ML.OnnxRuntime.Tests.Common\TrainingTest.cs(34,81): error CS0103: The name 'CheckpointState' does not exist in the current context [D:\a\_work\onnxruntime\onnxruntime\csharp\test\Microsoft.ML.OnnxRuntime.Tests.NetCoreApp\Microsoft.ML.OnnxRuntime.Tests.NetCoreApp.csproj]
```
Then I checked the code. I couldn't understand how it worked before. In
this build, `__TRAINING_ENABLED_NATIVE_BUILD__` is not defined. But the
"CheckpointState" class is defined in
https://github.com/microsoft/onnxruntime/blob/main/csharp/src/Microsoft.ML.OnnxRuntime/Training/CheckpointState.shared.cs#L21
And the file is empty when __TRAINING_ENABLED_NATIVE_BUILD__ is not
defined. So I don't understand how it could work in a normal build
without dnnl.

Here is my build command:

```
python tools\ci_build\build.py  --config RelWithDebInfo --build_dir dnnlbuild --skip_submodule_sync --build_csharp --parallel --use_binskim_compliant_compile_flags --cmake_generator "Visual Studio 17 2022" --build_shared_lib --enable_onnx_tests --build_wheel --msbuild_extra_options "IncludeMobileTargets=false" --build_nuget --use_vcpkg --use_vcpkg_ms_internal_asset_cache --use_dnnl
```

This PR removes the failed test.