[AIX] Not enabling ABSL_ENABLE_INSTALL for AIX to fix the build failure (#24910)
### Description
Recent changes in abseil-cpp.cmake is enabling ABSL_ENABLE_INSTALL which
is causing compilation error for AIX.
But the same was working before, so blocking this enablement.

```
[ 83%] Linking CXX executable onnxruntime_perf_test
ld: 0706-006 Cannot find or open library file: -l absl_failure_signal_handler
	ld:open(): A file or directory in the path name does not exist.
ld: 0706-006 Cannot find or open library file: -l absl_examine_stack
	ld:open(): A file or directory in the path name does not exist.
ld: 0706-006 Cannot find or open library file: -l absl_flags_parse
	ld:open(): A file or directory in the path name does not exist.
ld: 0706-006 Cannot find or open library file: -l absl_flags_usage
	ld:open(): A file or directory in the path name does not exist.
ld: 0706-006 Cannot find or open library file: -l absl_flags_usage_internal
	ld:open(): A file or directory in the path name does not exist.
.ibm-clang: error: linker command failed with exit code 255 (use -v to see invocation)
```


### Motivation and Context
To fix the compilation error, blocking the enablement of
ABSL_ENABLE_INSTALL under AIX.